### PR TITLE
testing coverage comment

### PR DESCRIPTION
**Pull request by andrew8bit**
playing around with some github actions

### CODE REVIEW

**Comment by andrew8bit** [comment]
Added a Github Action to check for test coverage. We can probably decide on a target the group wants to take, maybe like >80% or something. 

Not sure how reliable or sensitive the bot is, but feel like we can use it as a general guide on what needs to be tested. 

Also really wish the bot would comment on the PR vs commenting on the commits. Also apologies for the super detailed commit messages lol. Repo for the action below.
[https://github.com/MishaKav/pytest-coverage-comment](https://github.com/MishaKav/pytest-coverage-comment)

**Review by nateshim-indico — APPROVED** [review]

**Comment by Scott771** [comment]
@andrew8bit Just curious-- we had `coverage` set up as part of the repo originally (see the README), have you run it and is it still working as expected? you just want to ensure that it's run one every PR?

**Comment by andrew8bit** [comment]
> @andrew8bit Just curious-- we had `coverage` set up as part of the repo originally (see the README), have you run it and is it still working as expected? you just want to ensure that it's run one every PR? I'd say if we add this, we can probably strip that functionality out?

part of this uses that coverage functionality, just in a way to run on every commit and comment for it, which is intended. we can remove that section in the README though and make note that it runs on commit instead of manually though!

**Comment by Scott771** [comment]
> > @andrew8bit Just curious-- we had `coverage` set up as part of the repo originally (see the README), have you run it and is it still working as expected? you just want to ensure that it's run one every PR? I'd say if we add this, we can probably strip that functionality out?
> 
> part of this uses that coverage functionality, just in a way to run on every commit and comment for it, which is intended. we can remove that section in the README though and make note that it runs on commit instead of manually though!

Cool-- yeah, just make sure it's ripped out of any requirements (if it's there) and from the README

**Pull request merged**
